apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
stringData:
  JWT_SECRET: your-secret-key
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapi
  template:
    metadata:
      labels:
        app: myapi
    spec:
      serviceAccountName: admin-sa
      containers:
      - name: myapi
        image: node:22-alpine
        command: [ "sh", "-c" ]
        args:
          - cd /web-app && sleep infinity
        ports:
        - containerPort: 3000
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: JWT_SECRET
        - name: PORT
          value: "3000"
        - name: DB_NAME
          value: "platform"
        - name: DB_HOST
          value: "mysql"
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        volumeMounts:
        - name: code
          mountPath: /web-app
      volumes:
      - name: code
        hostPath:
          path: /run/desktop/mnt/host/c/Users/linsk/Desktop/web-app
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: myapi-service
spec:
  type: NodePort
  selector:
    app: myapi
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000