apiVersion: v1
kind: Service
metadata:
  name: jupyter-svc
spec:
  type: LoadBalancer
  selector:
    app: jupyter
    user: {{username}}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
      user: {{username}}
  template:
    metadata:
      labels:
        app: jupyter
        user: {{username}}
    spec:
      containers:
        - name: notebook
          image: jupyter/base-notebook:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          env:
            - name: JUPYTER_TOKEN
              value: "{{token}}"
          volumeMounts:
            - name: workdir
              mountPath: /home/{{username}}/work
      volumes:
        - name: workdir
          persistentVolumeClaim:
            claimName: {{pvcname}}