apiVersion: v1
kind: Pod
metadata:
  name: ros2-slam-unity
  labels:
    user: {{username}}
    app: pros_app
spec:
  containers:
    - name: rplidar
      image: "{{registry}}/screamlab/pros_jetson_driver_image:0.1.0"
      envFrom:
        - configMapRef:
            name: slam-unity-env-config
      volumeMounts:
        - name: demo-volume
          mountPath: /workspace
      command: ["/bin/bash", "-c"]
      args:
        - |
          source /opt/ros/humble/setup.bash && \
          source /workspaces/install/setup.bash && \
          ros2 launch /workspace/pros_app/docker/compose/demo/rplidar_unity.xml

    # -------------------- lidar-transform service --------------------
    - name: lidar-transform
      image: "{{registry}}/screamlab/pros_unity_lidar_trans_image:latest"
      envFrom:
        - configMapRef:
            name: slam-unity-env-config
      command: ["/bin/bash", "-c"]
      args:
        - |
          source /opt/ros/humble/setup.bash && \
          source /workspaces/install/setup.bash && \
          ros2 run unity_lidar_transformer lidar_transformer_node

    # # -------------------- slam service --------------------
    - name: slam
      image: "{{registry}}/screamlab/pros_jetson_driver_image:0.1.0"
      envFrom:
        - configMapRef:
            name: slam-unity-env-config
      volumeMounts:
        - name: demo-volume
          mountPath: /workspace
      command: ["/bin/bash", "-c"]
      args:
        - |
          source /opt/ros/humble/setup.bash && \
          source /workspaces/install/setup.bash && \
          ros2 launch /workspace/pros_app/docker/compose/demo/slam.xml

    # -------------------- rosbridge service --------------------
    - name: rosbridge
      image: "{{registry}}/screamlab/pros_jetson_driver_image:0.1.0"
      envFrom:
        - configMapRef:
            name: slam-unity-env-config
      ports:
        - containerPort: 9090
      command: ["/bin/bash", "-c"]
      args:
        - |
          source /opt/ros/humble/setup.bash && \
          source /workspaces/install/setup.bash && \
          ros2 launch rosbridge_server rosbridge_websocket_launch.xml
  # -------------------- Shared volume definition --------------------
  volumes:
    - name: demo-volume
      persistentVolumeClaim:
        claimName: {{pvcname}}
---
# Environment variable configuration (must create ConfigMap first)
apiVersion: v1
kind: ConfigMap
metadata:
  name: slam-unity-env-config
data:
  ROS_DOMAIN_ID: "1"
  ROS_DISCOVERY_SERVER: "{{discoveryip}}:11811"
  RMW_IMPLEMENTATION: "rmw_fastrtps_cpp"
  ROS_SUPER_CLIENT: "true"