apiVersion: v1
kind: Pod
metadata:
  name: ros2-yolo
  labels:
    user: {{username}}
    app: ros2_yolo
spec:
  containers:
    - name: pros-cameraapi
      image: "{{registry}}/screamlab/pros_cameraapi:0.0.2"
      command: ["/bin/bash", "-c", "--"]
      args: ["trap : TERM INT; sleep infinity & wait"]
      envFrom:
        - configMapRef:
            name: yolo-env
      volumeMounts:
        - name: volume
          mountPath: /workspaces/src
          subPath: ros2_yolo_integration/src
        - name: volume
          mountPath: /workspaces/screenshots
          subPath: ros2_yolo_integration/screenshots          
        - name: volume
          mountPath: /workspaces/fps_screenshots
          subPath: ros2_yolo_integration/fps_screenshots  
      resources:
        requests:
          memory: "256Mi"
        # limits:
        #   nvidia.com/gpu.shared: 1
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: {{pvcname}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: yolo-env
data:
  ROS_DOMAIN_ID: "1"
  ROS_DISCOVERY_SERVER: "ros2-discovery-server:11811"
  RMW_IMPLEMENTATION: "rmw_fastrtps_cpp"
  ROS_SUPER_CLIENT: "true"